image: Ubuntu2004

build_script:
  - ps: ./build.ps1

artifacts:
  - path: ./msbuild.log
  - path: ./artifacts/*.*nupkg

skip_tags: true

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master
